name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installing package list
        run: apt list --installed   
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install pyvirtualdisplay undetected-chromedriver
      - name: Install xvfb
        run: sudo apt-get install xvfb
        
      - name: Removing previous chrome instances on runner 
        run: |
           sudo apt purge google-chrome-stable && rm -rf youtube*.zip
           curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo dpkg -i google-chrome-stable_current_amd64.deb
           sudo rm -rf google-chrome-stable_current_amd64.deb
           google-chrome --version
           /usr/bin/google-chrome --version
           sudo chmod +x bin/v2ray
        
      - name: Running the Python script
        run: |
           curl -L https://github.com/362227/Python-Selenium-Action/raw/main/gost > gost && sudo chmod 755 ./gost && ./gost -L=:1087 ${{ secrets.GOST_GITHUB_GOST }} &
           sleep 5 && echo 代理ip：&& curl --proxy 127.0.0.1:1087 ifconfig.me
           #curl -L ${{ secrets.KY_GITHUB_URL }} > bin/ky-github.json && bin/v2ray -config bin/ky-github.json & sleep 2 && python run.py
           #curl -L ${{ secrets.KY_GITHUB_URL }} > bin/ky-github.json && bin/v2ray -config bin/ky-github.json &
           sleep 4
           #抓javgg
           python uc.py https://sharemania.us/ | tee sharemania.html

           
           #删除bin/ky-github.json
           rm -rf bin/ky-github.json
           
           
        
      - name: Commit and Push The Results From Python Selenium Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "GitHub Actions Results added"
         git push
